services:

  apache_php_mysql_mongodb:
    image: ebota/daw:apache_php_mysql_mongodb
    
    ports:
      - "8080:80"

    volumes:
      - ./php:/var/www/html

    command: /bin/bash -c "composer install --no-interaction --no-plugins --no-scripts && echo WEBSERVER_________UP_________AND_______RUNNIIIIIIING && apache2-foreground"

    environment:
      - VAR1=${VAR1}
      - VAR2=${VAR2}
      - MONGODB_URI=${MONGODB_URI}

    depends_on:
      - db


  db:
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: ${VAR3}
      MYSQL_USER: ${VAR1}
      MYSQL_PASSWORD: ${VAR2}
      LANG: C.UTF-8
    
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${VAR1}
      MONGO_INITDB_ROOT_PASSWORD: ${VAR2}

  mongo-express:
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${VAR1}:${VAR2}@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongodb_data:
