-- Codificació --
SET NAMES utf8mb4;

-- Crear Database --

CREATE DATABASE IF NOT EXISTS incidenciesDB
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

-- Donar Permisos --
GRANT ALL PRIVILEGES ON incidenciesDB.* TO 'usuari'@'%';
FLUSH PRIVILEGES;

-- Utilitzar la DB --
USE incidenciesDB;

-- Esborrem si les taules existeixen --
DROP TABLE IF EXISTS INCIDENCIA;
DROP TABLE IF EXISTS ACTUACIO;
DROP TABLE IF EXISTS DEPARTAMENT;
DROP TABLE IF EXISTS TECNIC;
DROP TABLE IF EXISTS TIPUS;

-- Creem les taules de nou --


CREATE TABLE DEPARTAMENT(
    ID_DEPT INT PRIMARY KEY AUTO_INCREMENT,
    NOM_DEPT VARCHAR(255) NOT NULL
);


CREATE TABLE TECNIC(
    ID_TECNIC INT PRIMARY KEY AUTO_INCREMENT,
    NOM_TECNIC VARCHAR(255) NOT NULL
);


CREATE TABLE TIPUS(
    ID_TIPUS INT PRIMARY KEY AUTO_INCREMENT,
    NOM_TIPUS VARCHAR(250) NOT NULL
);


CREATE TABLE ACTUACIO(
    ID_ACTUACIO INT PRIMARY KEY AUTO_INCREMENT,
    DATA_ACTUACIO TIMESTAMP NOT NULL,
    DESC_ACTUACIO VARCHAR(500),
    TEMPS INT,
    ES_VISIBLE BOOLEAN NOT NULL,
    ID_INCIDENCIA INT NOT NULL
);


CREATE TABLE INCIDENCIA(
    ID_INCIDENCIA INT PRIMARY KEY AUTO_INCREMENT,
    PRIORITAT ENUM('Alt', 'Mitjana', 'Baixa'),
    DATA_INICI DATE NOT NULL,
    DATA_FI TIMESTAMP,
    DESC_INCIDENCIA VARCHAR(255) NOT NULL,
    ID_DEPT INT NOT NULL,
    ID_TIPUS INT NOT NULL,
    ID_TECNIC INT NULL
);



-- Afegim Foreign Keys

ALTER TABLE INCIDENCIA ADD FOREIGN KEY (ID_DEPT) REFERENCES DEPARTAMENT(ID_DEPT) ON DELETE CASCADE;
ALTER TABLE INCIDENCIA ADD FOREIGN KEY (ID_TIPUS) REFERENCES TIPUS(ID_TIPUS) ON DELETE CASCADE;
ALTER TABLE INCIDENCIA ADD FOREIGN KEY (ID_TECNIC) REFERENCES TECNIC(ID_TECNIC) ON DELETE SET NULL;
ALTER TABLE ACTUACIO ADD FOREIGN KEY (ID_INCIDENCIA) REFERENCES INCIDENCIA(ID_INCIDENCIA) ON DELETE SET NULL;


--Afegim les dades 
INSERT INTO DEPARTAMENT (NOM_DEPT) VALUES 
    ('Llengua Anglesa'),
    ('Llengua Catalana'),
    ('Història'),
    ('Biologia'),
    ('Matemàtiques'),
    ('Informàtica'),
    ('Administració'),
    ('Direcció'),
    ('Altres');

INSERT INTO TIPUS (NOM_TIPUS) VALUES
    ('Hardware'),
    ('Software'),
    ('Xarxa'),
    ('Perifèrics'),
    ('Altres');

    INSERT INTO TECNIC (NOM_TECNIC) VALUES 
    ('Ermengol'),
    ('Àlvaro'),
    ('Gerard');